In [1]:
import scipy.io
tdt2 = scipy.io.loadmat('TDT2.mat')
reuter= scipy.io.loadmat('Reuters21578.mat')

In [2]:
tdt2

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Apr 25 13:53:55 2007',
 '__version__': '1.0',
 '__globals__': [],
 'gnd': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [30],
        [30],
        [30]], dtype=uint8),
 'fea': <9394x36771 sparse matrix of type '<class 'numpy.float64'>'
 	with 1224135 stored elements in Compressed Sparse Column format>}

In [3]:
sparse= tdt2['fea']
sparse

<9394x36771 sparse matrix of type '<class 'numpy.float64'>'
	with 1224135 stored elements in Compressed Sparse Column format>

In [4]:
matris= sparse.todense()
matris

matrix([[2., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 2., 0., ..., 0., 0., 0.],
        [0., 2., 2., ..., 0., 0., 0.]])

In [5]:
len(matris)

9394

In [6]:
label= tdt2['gnd']
label

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [30],
       [30],
       [30]], dtype=uint8)

In [7]:
y= len(label)
y

9394

In [8]:
#dorost kardane last10/top10 az tdt2
top10=0
for i in range (0,y-1):
    if label[i]== 1 or label[i]== 2 or label[i]== 3 or label[i]== 4 or label[i]== 5 or label[i]== 6 or label[i]== 7 or  label[i]== 8 or label[i]== 9 or label[i]== 10 : top10 = top10  +1        
   
#
print('number of top10 is:') 
top10

number of top10 is:


7456

In [9]:
matris_top10= matris[0:7455]
matris_top10

matrix([[2., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 3., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
import pandas as pd
tdt2_top10= pd.DataFrame(matris_top10)
tdt2_top10

0      1      2      3      4      5      6      7      8      9      \
0       2.0    1.0    0.0    0.0    1.0    0.0    0.0    0.0    1.0    0.0   
1       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2       0.0    0.0    0.0    0.0    1.0    0.0    0.0    2.0    0.0    0.0   
3       0.0    1.0    0.0    0.0    2.0    0.0    0.0    0.0    1.0    0.0   
4       0.0    1.0    1.0    0.0    1.0    0.0    0.0    2.0    0.0    0.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
7450    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7451    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7452    0.0    3.0    0.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0   
7453    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7454    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  36761  36762  36763  36764  36765  36766  36767  36768  36769  \
0     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
7450  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7451  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7452  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7453  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7454  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      36770  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
7450    0.0  
7451    0.0  
7452    0.0  
7453    0.0  
7454    0.0  

[7455 rows x 36771 columns]

In [11]:
last10=0
for i in range (0,y-1):
    if label[i]== 30 or label[i]== 29 or label[i]== 28 or label[i]== 27 or label[i]== 26 or label[i]== 25 or label[i]== 24 or label[i]== 23 or label[i]== 22 or  label[i]== 21 : last10 = last10+1        

print('number of last10 is:') 
last10 

number of last10 is:


652

In [12]:
matris_last10= matris[-653:-1]
matris_last10

matrix([[8., 5., 1., ..., 0., 0., 0.],
        [9., 0., 1., ..., 0., 0., 0.],
        [4., 2., 1., ..., 0., 0., 0.],
        ...,
        [0., 1., 2., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 2., 0., ..., 0., 0., 0.]])

In [13]:
tdt2_last10= pd.DataFrame(matris_last10)

In [14]:
reuter

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Jan 16 00:53:49 2008',
 '__version__': '1.0',
 '__globals__': [],
 'gnd': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [63],
        [64],
        [65]], dtype=uint8),
 'trainIdx': array([[   1],
        [   2],
        [   3],
        ...,
        [8286],
        [8288],
        [8290]], dtype=uint16),
 'testIdx': array([[2674],
        [2675],
        [2676],
        ...,
        [8291],
        [8292],
        [8293]], dtype=uint16),
 'fea': <8293x18933 sparse matrix of type '<class 'numpy.float64'>'
 	with 389455 stored elements in Compressed Sparse Column format>}

In [15]:
reuter['fea']

<8293x18933 sparse matrix of type '<class 'numpy.float64'>'
	with 389455 stored elements in Compressed Sparse Column format>

In [16]:
matrisr= reuter['fea'].todense()
matrisr

matrix([[1., 1., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]])

In [17]:
labelr= reuter['gnd']
labelr

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [63],
       [64],
       [65]], dtype=uint8)

In [18]:
z= len(reuter['gnd'])
z

8293

In [19]:
def func(a):
    x=0
    for i in range (0,8292):
        if labelr[i] == a :
            x = x+1 
    z = int(x)
    return z

#tedade har label
print(func(1),func(2),func(3),func(4),func(5),func(6),func(7),func(8),func(9),func(10))


3713 2055 321 298 245 197 142 114 110 90


In [20]:
#category1
cat1=matrisr[0:func(1)-1]
cat1

matrix([[1., 1., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 9., 7., ..., 0., 0., 0.],
        [1., 2., 0., ..., 0., 0., 0.],
        [1., 6., 0., ..., 0., 0., 0.]])

In [21]:
import pandas as pd
cat1= pd.DataFrame(cat1)
cat1

0      1      2      3      4      5      6      7      8      9      \
0       1.0    1.0    1.0    3.0    8.0    3.0    0.0    2.0    0.0    0.0   
1       1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0   
2       1.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    1.0    0.0   
3       1.0    2.0    1.0    1.0    2.0    1.0    0.0    1.0    0.0    0.0   
4       1.0    0.0    1.0    3.0    8.0    2.0    0.0    2.0    0.0    0.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3707    1.0    0.0    0.0    1.0    1.0    1.0    0.0    1.0    1.0    0.0   
3708    1.0    4.0    5.0    3.0    9.0    2.0    0.0    4.0    0.0    0.0   
3709    1.0    9.0    7.0    9.0    6.0    3.0    0.0    2.0    0.0    1.0   
3710    1.0    2.0    0.0    2.0    3.0    1.0    0.0    1.0    0.0    0.0   
3711    1.0    6.0    0.0    2.0    3.0    1.0    0.0    1.0    0.0    0.0   

      ...  18923  18924  18925  18926  18927  18928  18929  18930  18931  \
0     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3707  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3708  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3709  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3710  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3711  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      18932  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
3707    0.0  
3708    0.0  
3709    0.0  
3710    0.0  
3711    0.0  

[3712 rows x 18933 columns]

In [22]:
cat1= cat1.sample(frac=0.05)
cat1

0      1      2      3      4      5      6      7      8      9      \
1633    1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0   
304     1.0    0.0    2.0    4.0    4.0    1.0    0.0    1.0    0.0    0.0   
3193    1.0    4.0    1.0    5.0    7.0    2.0    0.0    2.0    0.0    0.0   
105     1.0    3.0    3.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
488     0.0   14.0    0.0    0.0   10.0    1.0    0.0    1.0    0.0    1.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2633    1.0    4.0    0.0    0.0    0.0    2.0    3.0    0.0    0.0    3.0   
642     1.0    2.0    4.0    1.0    0.0    1.0    1.0    0.0    3.0    4.0   
2566    1.0    0.0    0.0    2.0    6.0    2.0    0.0    2.0    0.0    0.0   
3692    1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0   
902     1.0    2.0    3.0    6.0    6.0    3.0    0.0    2.0    0.0    1.0   

      ...  18923  18924  18925  18926  18927  18928  18929  18930  18931  \
1633  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
304   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3193  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
105   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
488   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2633  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
642   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2566  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3692  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
902   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      18932  
1633    0.0  
304     0.0  
3193    0.0  
105     0.0  
488     0.0  
...     ...  
2633    0.0  
642     0.0  
2566    0.0  
3692    0.0  
902     0.0  

[186 rows x 18933 columns]

In [23]:

cat2= matrisr[func(1):func(1)+func(2)]
cat2= pd.DataFrame(cat2)
cat2= cat2.sample(frac=0.1)

cat3= matrisr[func(1)+func(2):func(1)+func(2)+func(3)]
cat3= pd.DataFrame(cat3)
cat3= cat3.sample(frac=0.4)

cat4= matrisr[func(1)+func(2)+func(3):func(1)+func(2)+func(3)+func(4)]
cat4= pd.DataFrame(cat4)
cat4= cat4.sample(frac=0.4)

cat5= matrisr[func(1)+func(2)+func(3)+func(4):func(1)+func(2)+func(3)+func(4)+func(5)]
cat5= pd.DataFrame(cat5)
cat5= cat5.sample(frac=0.4)

cat6= matrisr[func(1)+func(2)+func(3)+func(4)+func(5):func(1)+func(2)+func(3)+func(4)+func(5)+func(6)]
cat6= pd.DataFrame(cat6)
cat6= cat6.sample(frac=0.4)

cat7= matrisr[func(1)+func(2)+func(3)+func(4)+func(5)+func(6):func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)]
cat7= pd.DataFrame(cat7)
cat7= cat7.sample(frac=0.4)

cat8= matrisr[func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7):func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)+func(8)]
cat8= pd.DataFrame(cat8)
cat8= cat8.sample(frac=0.4)

cat9= matrisr[func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)+func(8):func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)+func(8)+func(9)]
cat9= pd.DataFrame(cat9)
cat9= cat9.sample(frac=0.4)

cat10= matrisr[func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)+func(8)+func(9):func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)+func(8)+func(9)+func(10)]
cat10= pd.DataFrame(cat10)
cat10= cat10.sample(frac=0.4)

In [24]:
Reuters_top10= pd.concat([cat1, cat2, cat3, cat4, cat5, cat6, cat7, cat8, cat9, cat10], ignore_index=True)
Reuters_top10

0      1      2      3      4      5      6      7      8      9      \
0      1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0   
1      1.0    0.0    2.0    4.0    4.0    1.0    0.0    1.0    0.0    0.0   
2      1.0    4.0    1.0    5.0    7.0    2.0    0.0    2.0    0.0    0.0   
3      1.0    3.0    3.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
4      0.0   14.0    0.0    0.0   10.0    1.0    0.0    1.0    0.0    1.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
994    1.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    2.0   
995    1.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0   
996    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    2.0    0.0   
997    1.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   
998    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    3.0   

     ...  18923  18924  18925  18926  18927  18928  18929  18930  18931  18932  
0    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
994  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
995  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
996  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
997  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
998  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[999 rows x 18933 columns]

In [25]:
func3to20 = (func(1)+func(2)+func(3)+func(4)+func(5)+func(6)+func(7)+func(8)+func(9)+func(10)
             +func(11)+func(12)+func(13)+func(14)+func(15)+func(16)+func(17)+func(18)+func(19)+func(20))
cat3to20 = matrisr[func(1)+func(2):func3to20]
cat3to20 = pd.DataFrame(cat3to20)

Reuters_top20 = pd.concat([cat1,cat2,cat3to20])
Reuters_top20

0      1      2      3      4      5      6      7      8      9      \
1633    1.0    0.0    0.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0   
304     1.0    0.0    2.0    4.0    4.0    1.0    0.0    1.0    0.0    0.0   
3193    1.0    4.0    1.0    5.0    7.0    2.0    0.0    2.0    0.0    0.0   
105     1.0    3.0    3.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
488     0.0   14.0    0.0    0.0   10.0    1.0    0.0    1.0    0.0    1.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2027    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2028    1.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0   
2029    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2030    1.0    2.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2031    1.0    1.0    1.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   

      ...  18923  18924  18925  18926  18927  18928  18929  18930  18931  \
1633  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
304   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3193  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
105   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
488   ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2027  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2028  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2029  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2030  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2031  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      18932  
1633    0.0  
304     0.0  
3193    0.0  
105     0.0  
488     0.0  
...     ...  
2027    0.0  
2028    0.0  
2029    0.0  
2030    0.0  
2031    0.0  

[2424 rows x 18933 columns]

In [26]:
from sklearn.decomposition import NMF
from sklearn.cluster import KMeans

In [27]:
import numpy as np

model = NMF(n_components=10, init='random', random_state=0)
W_tt10 = model.fit_transform(tdt2_top10)  
H_tt10 = model.components_

In [28]:
y_predict_tt10 = []
for data in range(len(tdt2_top10)):
    y_predict_tt10.append(np.argmax(H_tt10[:,data]))
y_predict_tt10 = np.asarray(y_predict_tt10)

In [30]:
kmeans_tt10 = KMeans(n_clusters=10, random_state=0).fit(tdt2_top10)

In [31]:
model = NMF(n_components=10, init='random', random_state=0)
W_tl10 = model.fit_transform(tdt2_last10)  
H_tl10 = model.components_

y_predict_tl10 = []
for data in range(len(tdt2_last10)):
    y_predict_tl10.append(np.argmax(H_tl10[:,data]))
y_predict_tl10 = np.asarray(y_predict_tl10)

kmeans_tl10 = KMeans(n_clusters=10, random_state=0).fit(tdt2_last10)

In [34]:
model = NMF(n_components=10, init='random', random_state=0)
W_rt10 = model.fit_transform(Reuters_top10)  
H_rt10 = model.components_

y_predict_rt10 = []
for data in range(len(Reuters_top10)):
    y_predict_rt10.append(np.argmax(H_rt10[:,data]))
y_predict_rt10 = np.asarray(y_predict_rt10)

kmeans_rt10 = KMeans(n_clusters=10, random_state=0).fit(Reuters_top10)

In [32]:
model = NMF(n_components=10, init='random', random_state=0)
W_rt20 = model.fit_transform(Reuters_top20)  
H_rt20 = model.components_

y_predict_rt20 = []
for data in range(len(Reuters_top20)):
    y_predict_rt20.append(np.argmax(H_rt20[:,data]))
y_predict_rt20 = np.asarray(y_predict_rt20)

kmeans_rt20 = KMeans(n_clusters=10, random_state=0).fit(Reuters_top20)

In [52]:
#W_rt20

In [53]:
#H_rt20

In [54]:
#y_predict_rt20

In [37]:
t4=kmeans_rt20.labels_
t4

In [36]:
p4=kmeans_rt20.fit_predict(Reuters_top20)
p4

In [44]:
# cluster=r=r0=10 
# tarife function purity

def purity(cluster, tlabel, plabel):
    
    docs = tlabel.size
    tedad_tlabel = np.unique(tlabel).size
    purity=0 
    
    for k in range(0,cluster): #sigma i=1 ...r
        nij=0
        nij_list=[]
        for j in range (0,tedad_tlabel): #baraye j ha: check kardane i ha
            for i in range(0,tlabel):
                if tlabel[i]==j and plabel[i]==k: nij=nij+1
            nij_list.append(nij)
        maxj= nij_list.sort.index
        purity= purity+ (maxj/docs)
        
    return purity

In [51]:
purity(10,t4,p4)

TypeError: only integer scalar arrays can be converted to a scalar index